// Code generated by "stringer -type=Level -output=level_string.go"; DO NOT EDIT.

package entry

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DEBUG-0]
	_ = x[INFO-1]
	_ = x[WARN-2]
	_ = x[ERROR-3]
	_ = x[FATAL-4]
}

const _Level_name = "DEBUGINFOWARNERRORFATAL"

var _Level_index = [...]uint8{0, 5, 9, 13, 18, 23}

func (i Level) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Level_index)-1 {
		return "Level(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Level_name[_Level_index[idx]:_Level_index[idx+1]]
}
